---
title: "Data Science in a Box Lab 4"
author: "Alex Lindquist, Nate Smullen, Wynter Malone, Yadhira Garcia"
date: "10/17/2022"
output: html_notebook
---

##Load Packages

```{r}
library(tidyverse)
library(dsbox)
```

```{r}
dn_ak <- dennys %>%
  filter(state == "AK")
nrow(dn_ak)
```
There are 3 Denny's in Alaska.

```{r}
lq_ak <- laquinta %>%
  filter(state == "AK")
nrow(lq_ak)
```
There are 2 LaQuintas in Alaska.

```{r}
dn_lq_ak <- full_join(dn_ak, lq_ak, by = "state")
dn_lq_ak
```
There are 6 observations in this joined dataframe, as there are 3 Denny's and 2
LaQuintas, so there are 6 total combinations of the two. The Denny's are 
represented with .x variable names whereas the LaQuintas are represented with 
the .y variable names.

```{r}
haversine <- function(long1, lat1, long2, lat2, round = 3) {
  # convert to radians
  long1 = long1 * pi / 180
  lat1  = lat1  * pi / 180
  long2 = long2 * pi / 180
  lat2  = lat2  * pi / 180
  
  R = 6371 # Earth mean radius in km
  
  a = sin((lat2 - lat1)/2)^2 + cos(lat1) * cos(lat2) * sin((long2 - long1)/2)^2
  d = R * 2 * asin(sqrt(a))
  
  return( round(d,round) ) # distance in km
}
```

```{r}
dn_lq_ak <- dn_lq_ak %>% mutate(distance = haversine(longitude.x, latitude.x, 
                                                     longitude.y, latitude.y))
```

```{r}
dn_lq_ak_mindist <- dn_lq_ak %>%
  group_by(address.x) %>%
  summarise(closest = min(distance))
```

```{r}
summary(dn_lq_ak_mindist)
dn_lq_ak_mindist %>% ggplot(aes(x=closest)) + geom_dotplot()
```




